### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [harjot-oberai/MusicDNA#63]
Greetings, I'm a graphic designer and I would love to contribute to your project with a new brand logo. This is completely free, take it as a contribution (which you can accept or not). In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think?, best regards. :)

**Comment by harjot-oberai** [comment]
I was actually thinking of releasing a v2 of the project, so a new logo would be really great.
Open the issue again and add all the iterations of the logo here. I will ask a friend of mine (designer) to review them as well.
